### ISSUE TITLE
Turning Movement

### ISSUE THREAD

**Issue by TropicMango** [liarch29/Re_name_me#3]
(speed * delta) works to keep the ship moving at a constant speed, but if delta changes the amount the ship can turn also changes. Since it turns at max radius for every step forward, there for the smaller the delta the more the ship can turn.

**Comment by TropicMango** [comment]
I was thinking that we can change the max turn constant to include the delta.

**Comment by Technius** [comment]
That's probably what we should do. One of us needs to find some time to write down and solve an equation for the movement.

**Comment by TropicMango** [comment]
Problem Solved

**Comment by TropicMango** [comment]
in turn_regulation
